modules/plugins/dkimVerifier.js

Simplified the plug-in.
The new plug-in version needs at least the 1.3.0 version of the DKIM Verifier.
This update is not time critical as the old plug-in version works also with the new DKIM Verifier version 1.3.0, thought there can occur some issues if the DKIM result is saved and both classic and conversation view is used.

updated plugin for DKIM Verifier

---

bootstrap.js

Unregister notifier on shutdown to avoid an error when uninstalling

---

skin/quickreply.css

I am not able to test this on Windows or Mac, but I believe it will look good there too.
fixes #982

Make the quick reply buttons conform to the system theme.

---

skin/conversation.css

Change #conversationHeader color to set it off from other content.

---

skin/quickreply.css

Changed color of backgrounds for Reply fields from buttonface to window
since it is in fact minimized window

Proper fix for issue #982

---

content/stub.compose-ui.js
content/stub.xhtml
locale/en-US/template.properties
modules/conversation.js
modules/hook.js
modules/message.js
modules/plugins/enigmail.js
skin/quickreply.css

I fixed bugs with Enigmail 1.9 change and quick reply.
This works with Enigmail 1.8.
More tests would be required for quick reply support.
This will fix #978 #845 #791 #1015.

Enigmail 1.9 and quick reply support

---

modules/message.js

Show 'reply-to' in the message details

---

content/stub.xhtml
locale/en-US/template.properties
modules/message.js
modules/plugins/enigmail.js
skin/conversation.css

* add notification bar UI to view signed status
* fix bugs with inline PGP on quick reply
* refactoring and trivial fix

Add notification bar UI and fix bugs with Enigmail

---

modules/plugins/enigmail.js

We use per-recipient rules to set default encrypt/sign status on
quick reply. This follows Enigmail behavior. Code is based on
enigmailMsgComposeOverlay.js in Enigmail.
`EnigmailConstants` is not available in Enigmail 1.8.2. We fixed
to work with 1.8.2.

Improve default encrypt/sign status on quick reply

---

content/stub.xhtml
skin/conversation.css

This implements some first steps for implementing the new design proposed in #967, namely:
- increase message header height
- remove rounded corners
- change shadows
@protz I do have some more in the pipeline. I am not sure whether you prefer many small or one big pull request. As I am not sure how much time I have in the next weeks I would prefer to do this in many small steps. This would reduce the threat of merge conflicts.

First steps for design update

---

content/stub.xhtml
modules/misc.js
skin/conversation.css
skin/quickreply.css

As a further step towards implementing the design from #967 I did some general CSS refactoring. This should only have minimal UI changes.

refactor CSS

---

content/stub.xhtml
skin/conversation.css

This adds some more UI changes for #967.
Next up I will take care of icons.

UI: round tags and flat buttons

---

LICENSE
content/stub.xhtml
modules/message.js
skin/conversation.css

I have some more changes for #967 locally, but I am not pleased with most of them yet. So this is a small collection of bits and bobs that can already be merged.

Some small UI changes

---

skin/conversation.css

add messageHeader margin

---

skin/conversation.css

This got reverted somewhere along #1165 or #1166

Reapply attachment icon rotation

---

content/stub.xhtml
modules/message.js

replace mainActionLink with icon

---

skin/conversation.css

I can not test on a mac either, but this should fix #987.

make sure that action buttons are centered

---

README.md

readme: replace reference to the old name

---

content/stub.compose-ui-bz.js
content/stub.compose-ui.js
package.json

This needs https://github.com/protz/thunderbird-stdlib/pull/17 to work correctly - combined, it should get master working again.

Update Conversations to work with the newer generators code / sync with stdlib.

---

modules/plugins/enigmail.js
modules/quoting.js

Fix for Thunderbird 60 and Enigmail 2.0.8.
- verify signed PGP MIME messages
- decrypt verify inline PGP messages
Quick reply with PGP doesn't work.

enigmail 2.0 support

---

content/assistant/assistant.xhtml
skin/assistant.css

Remove jQuery from the setup assistant.

---

content/stub.compose-ui.js

replace filePicker.show with open since it's been deprecated

---

.travis.yml

We should be able to do this with this patch, just testing before pushing to master.

Switch to the latest version of node for running tests on Travis

---

.eslintrc.js
.gitignore
babel.config.js
build.sh
content/gallery/gallery.jsx
content/gallery/index.html
package-lock.json
package.json

Since we're now using react, it'd be easier to use jsx for constructing the elements.
`build.sh` isn't the best way of managing the build but it'll do for now.

Switch to using jsx for React components.

---

addon/content/contactDetail.jsx
addon/content/message.jsx
addon/content/messageList.jsx
addon/content/messageTags.jsx
addon/content/modules/message.js
addon/content/reducer.js

Add basic keyboard navigation to the conversations view. This address issue #1428

Added keyboard navigation

---

addon/content/conversationHeader.jsx
addon/content/messageTags.jsx
addon/content/modules/conversation.js
addon/content/modules/log.js
addon/content/modules/message.js
addon/content/modules/monkeypatch.js
addon/content/modules/plugins/enigmail.js
addon/content/reducer.js
addon/content/stub.completion-ui.js
addon/content/stub.compose-ui.js
addon/experiment-api/api.js
addon/experiment-api/schema.json
addon/manifest.json
addon/prefs.js
addon/tests/messageTags.test.jsx

This is a follow-on to #1465. It starts to replace some more msgHdrUtils uses, and also starts to simplify error logging which also provides more integrated output.

Remove some more msgHdrUtils deps, start cleaning up logging

---

addon/content/es-modules/utils.js
addon/content/modules/contact.js
addon/content/stub.xhtml
addon/content/utils.js
addon/tests/utils.test.jsx

This PR starts splitting code out of `contact.js` that doesn't need to be privileged.

Separated out utility functions from `contact.js` and added tests

---

addon/_locales/hr/messages.json

A fix and update of the Croatian translation of the add-on.

Update and fix Croatian translation

---

addon/_locales/uk/messages.json

Updated translation according to the latest changes.

Update Ukrainian translation

---

addon/background/window.js
addon/content/components/message/messageTags.jsx
addon/content/conversation.css
addon/experiment-api/msgWindowApi.js
addon/experiment-api/msgWindowSchema.json
addon/tests/messageTags.test.jsx

- add listener for an `addPill` message, which allows other add-ons to add tags
- started to remove/replace DKIM plugin specific stuff
#1431 #1590

Allow other addons to add pills via message API

---

addon/content/components/message/messageDetails.jsx
addon/content/components/message/messageHeader.jsx
addon/content/reducer/conversationUtils.js

Fixes #1803 
I had a poke around with the email and found it would crash with the "Forward this conversation" button so fixed that too.

Fix crash when opening email with empty From header

---

addon/_locales/tr/messages.json

Hello,
Please find the updated Turkish translations on this Pull request. All missing fields should be added within this PR.
Thanks in advance!

Turkish Translations updated

---

addon/_locales/hu/messages.json

Added Hungarian translation for the Thunderbird Conversations extension. This file includes translations for UI elements, tooltips, and other interface texts.

Create Hungarian localization for messages.json
