- modules/message.js
I see the same issue with #980.
`this` causes an error. Instead we use `self`.
Fixes #980
> Fix attachments showing with PGP/MIME messages

- modules/conversation.js
- modules/message.js
PGP encrypted message is always `aGlodaMsg.isEncrypted == false`
for some reason.
As a workaround, we check content type.
> Fix isEncrypted false of PGP encrypted message

- modules/plugins/enigmail.js
I fixed the following issue.
* inline PGP verification fails if a message has collapsed quoted text
* encrypt/sign mode changed manually is not always used on quick reply
And I did some refactoring and updated code from latest Enigmail source.
> Fix inline PGP verification and quick reply with Enigmail

- content/stub.completion-ui.js
- content/stub.compose-ui.js
- content/stub.xhtml
We change the order of declaration to fix redeclaration and
reference errors.
`asToken` in stub.completion-ui.js is referenced in
stub.compose-ui.js. So we change to include stub.completion-ui.js
first.
Top-level const/let is lexical scope on trunk.
https://bugzilla.mozilla.org/show_bug.cgi?id=1209777
> Fix errors on quick reply with trunk

- modules/message.js
- modules/plugins/enigmail.js
When I executed expand all messages, PGP/MIME messages in the
conversation was blank. If `lastMsgUri` is set, decrypting
messages other than `lastMsgUri` stops on Enigmail side.
It seems that this was changed on Enigmail at some point.
`lastMsgUri` is set from `Enigmail.msg.getCurrentMsgUriSpec`.
We remove these code to decrypt properly.
Security info display doesn't need `lastMsgUri` now.
This may fix #1020.
> Fix blank body of PGP/MIME messages

- content/stub.completion-ui.js
This fixes:
Timestamp: 02/17/2016 02:46:52 PM
Error: TypeError: entries(...).map is not a function
Source File: chrome://conversations/content/stub.completion-ui.js
Line: 96
And allows to see the suggested contacts when adding a new contact to an email!
> Fix suggestions when adding a new contact to an email.

- modules/plugins/enigmail.js
With Enigmail 1.9.1 a reference error is caused when composing quick reply.
We set dummy `gSMFields` to fix the reference error.
Error log:
```
2016-04-28 10:48:28     Conversations.Stub      WARN    Plugin returned an error: ReferenceError: gSMFields is not defined
2016-04-28 10:48:28     Conversations   DEBUG
Enigmail.msg.processFinalState@chrome://enigmail/content/enigmailMsgComposeOverlay.js:1431:1
_enigmailHook_onComposeSessionChanged@resource://conversations/modules/plugins/enigmail.js:904:5
ComposeSession.prototype.setupDone@chrome://conversations/content/stub.compose-ui.js:740:13
ComposeSession.prototype.setupAutocomplete/<.reply/showHideActions@chrome://conversations/content/stub.compose-ui.js:664:11
ComposeSession.prototype.changeComposeFields/<@chrome://conversations/content/stu …
```
> Fix ReferenceError: gSMFields is not defined

- README.md
- install.rdf
- modules/message.js
- other/oembed-addon/install.rdf
replaced all `GMail-Conversation-View` strings by `thunderbird-conversations`
- helps to avoid confusion in addon detail view
- links don't need redirect anmyore
> replaced all references to the old name

- skin/conversation.css
I often need to copy the sender email address. This is an issue if it is long because the button is hidden behind the picture. This change will allow the line to break and make the button usable again.
Note that I did only try this with 2.10.2 as I am stuck with thunderbird 38.
> allow to break author Email

- content/stub.xhtml
- skin/conversation.css
This fixes overflowing of email author's name and address, see screenshots what happens when they are too wide (overflow ellipsis). The button to copy the email address is always visible now, too, and not hidden by the picture.
> Layout enhancements of email authors and recipients tooltip

- modules/assistant.js
- modules/monkeypatch.js
This should reintroduce the 'between'-column, which is indeed better than the correspondents-column btw.
Incidentally, I updated stdlib
> Reintroduce between column

- skin/conversation.css
- skin/quickreply.css
As mentioned in https://github.com/protz/thunderbird-conversations/issues/967#issuecomment-272686468, there is a problem with link colors if the chrome and composition colors are significantly different. This change might be a way to fix that: For the chrome, use `-moz-nativehyperlinktext` instead of `-moz-HyperlinkText`. 
Note that the value for `-moz-HyperlinkText` can be controlled from the UI (Preferences -> Display -> Formatting -> Colors). The matching background color is however not exposed to CSS (As far as I know).
I am not completely sure if this is a good idea. It should be tested with some different setups.
> use nativehyperlinktext color

- content/quickReply.js
- content/stub.compose-ui.js
- content/stub.xhtml
- locale/en-US/template.properties
- skin/conversation.css
- skin/quickreply.css
I finally good around to work on the footer part of #967. I was actually able to get rid of a lot of code without losing any functionality by just reusing existing parts.
The main change (apart from a lot of styling) is that `.footerActions` is now used in both "normal" messages and quick reply. They also replace the little "open in new window" buttons in the corner of the quick reply textareas. This way there is less code and more UI consitency -- win-win!
I removed one transition (opening a quickreply editor). The issue was that when both textareas are present, the first one still starts out with 100% width and transitions down to 50%. That was just anoying. This issue exists in master.
> Update footer styling

- skin/conversation.css
Labelicious! Blatantly stolen from @xi's original mockup (5459a32).  
I'm not quite sure but the alignment seems to be off for collapsed messages.
Screen includes changes from #1157.
> New tag/label design

- content/stub.xhtml
- modules/contact.js
- modules/message.js
- skin/conversation.css
**Please do not merge this yet!**
In #967 there are colors cricles with the initials of the sender on each message. This is a first draft of that.
There are two main challanges here:
1. Get the initials from the name/email
2. Get the color for a contact
Interestingly, I did not find any tutorials of how to do this online. But maybe I just used the wrong searchterms…
About (1): There are many issues here. For one, what we have as a name may well be an email adress, a nickname or some auto generated string (e.g. `name at gmail.com`). Second, the semantics of the name are highly dependent on locale. I did some initial draft algorithm, but we should properly test it before merging.
About (2): With the previous implementation, the same person could have a different color in a different …
> RFC: contact initials in UI

- modules/contact.js
One person I get emails from has changed their name field to:
first last 🐧
Currently, this causes conversations to hang and throw out a bunch of errors. This is because the initials handling code is not taking account of the utf-8 character.
developer.mozilla.org had a suggest way around this, so I've added that to the code.
> Fix an issue displaying initials that contain utf-8 characters that causes the message display to hang.

- modules/message.js
- skin/conversation.css
Fixes #1178.
The issue was that there was a naming conflict with SVG icons (which also use the `.icon` class). 6cbae7c1 made them non-clickable.
> rename attachment icon to .mime-icon

- modules/plugins/glodaAttrProviders.js
Bug 1292569 made a change to gloda's indexer.js that means it now requires proper generators to work correctly.
I noticed this due to a `TypeError: this.activeIndexer.return is not a function` message on the error console.
This change gets the indexer running again in 52.
> Fixes #1184: Change process functions for gloda to generators to account for changes made in Thunderbird bug 1292569.

- content/stub.compose-ui-bz.js
This seems to be an issue on latest master - selecting a Bugzilla message results in an email view, that is mostly complete, but significantly the email doesn't get marked as read.
Looks like something changed the class names and broke the selector rules, and in turn this broke updating the display.
This seems to fix it for me.
> Update the querySelector for looking at bugzilla emails, so that selecting them works again.

- .eslintignore
- .eslintrc.js
- .gitignore
- .travis.yml
- content/pdfviewer/viewer.js
- content/stub.compose-ui-bz.js
- content/stub.compose-ui.js
- modules/assistant.js
- modules/message.js
- modules/monkeypatch.js
- modules/quoting.js
- other/oembed-addon/bootstrap.js
- package-lock.json
- package.json
@protz, this does the minimum necessary to enable ESLint on the repository.
I've included eslint-plugin-mozilla as I think we'll want that, and I added the mozilla/recommended configuration as a default one. I've turned off the rules where we fail.
The code changes are mainly things where we were using array comprehensions & other non-standard javascript items. The Firefox code base has moved away from these, so I think it is sensible to do that here as well.
Can you enable Travis CI on this repository? Just visit https://travis-ci.org/ and sign-in, then go to account and flip the switch for the repository.
Once we've got one test run reported, it would be nice to turn on master as a protected branch in github and require the tests to pass to merge PRs.
> Enable ESLint using the mozilla/recommended rules.

- modules/message.js
Hence cmd-A (but not just 'A') is passed up the event chain in the preview panel and works correctly as select-all.
> Fixes #1195: Correct the modifier matching actions for keypresses so that it works correctly

- skin/conversation.css
When the contact photo does not have a quadratic size, the leftmost excerpt is shown. As contact photos usually contains centered pictures of a person's face, it is not helpful to start showing the photo from the left. Instead, it should be centered and the center portion should be shown.
> Center contact photo

- .eslintignore
- .gitignore
- .gitmodules
- README.md
- build.sh
- content/pdfviewer/viewer.xhtml
- package-lock.json
- package.json
Using pdfjs-dist is a slightly better way of getting "official" builds, in that we can prove reproducible builds to make AMO happy.
> chore(build): Switch to using pdfjs-dist from npm for getting pdf*.js files.

- .eslintrc.js
- bootstrap.js
- content/.eslintrc.js
- content/gallery/js/gallery.js
- defaults/preferences/defaults.js
- modules/assistant.js
- modules/contact.js
- modules/conversation.js
- modules/keycustomization.js
- modules/log.js
- modules/message.js
- modules/misc.js
- modules/monkeypatch.js
- modules/plugins/embeds.js
- modules/plugins/enigmail.js
- modules/plugins/glodaAttrProviders.js
- modules/plugins/helpers.js
- modules/plugins/lightning.js
- modules/prefs.js
- modules/quoting.js
- other/oembed-addon/bootstrap.js
This enables the no-undef rule for everything apart from content/. I think it may be possible to clean up some of the imports further, but we'll see to that later.
Additionally note that as eslint-plugin-mozilla doesn't support Thunderbird's modules, I'm changing the style of import to be explicit variables.
> Fix(general): Enable the no-undef rule for most of the add-on.

- modules/plugins/enigmail.js
Handle SMIME signed messages like enigmail to avoid empty body.
I could reproduce empty body with a SMIME signed message.
This will fix #1240.
> Handle SMIME message in enigmail.js

- content/handlebars-wrapper.js
- content/stub.completion-ui.js
- content/stub.xhtml
- modules/message.js
- modules/misc.js
- modules/prefs.js
- modules/quoting.js
String.x is deprecated: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Deprecated_String_generics
Also folder.prettiestName is reporting as deprecated as well.
There's still others to fix, but we can leave those for later.
@protz please can you look over this, especially the String.* changes.
> Clean up some deprecated APIs usage

- modules/quoting.js
Based on my painful inbox, newer outlook versions slightly changed the shade of this horizontal line, so we need to refine the check a little.
The HTML still looks entirely generic with nothing better to select against, though.
> Update Outlook blockquote detection for newer versions

- modules/plugins/enigmail.js
The API for Engimail.msg.messageDecryptCb has changed with Enigmail v2.0. This patch adopts to the change (and fixes the Enigmail bug https://sourceforge.net/p/enigmail/bugs/894/).
> Adopt decryption to API of Enigmail 2.0

- addon/content/assistant/assistant.xhtml
- addon/content/messageHeaderOptions.jsx
- addon/modules/message.js
This is essentially are fixes of some of the warnings [reported here](https://lgtm.com/projects/g/protz/thunderbird-conversations/alerts/?mode=tree).
Commit `content: expand menu in displayMenu` may need a bit of attention in case I'm missing something.
> LGTM warnings fixes

- babel.config.js
- package.json
The 'esmodules' definition equates to Firefox 60 or later, [see here](https://github.com/babel/babel/blob/9febf6388233c3d23d4fa9deca5ca8f682567573/packages/babel-preset-env/data/built-in-modules.json).
This currently means the generated code has changes such as async/await swapped into generators, arrow functions replaced and more.
Whilst this probably doesn't matter too much, I think I'd rather keep the changes minimal and let the generated code use all the features of js that are available in the minimum version that we support (68). There's would be a slight reduction in file size, maybe some very small performance advantages as well (due to not having polyfill functions).
@siefkenj can you see any reason not to do this?
> Change Babel configuration to work for just Firefox 68 or later, since that is what we currently support.

- addon/content/attachments.jsx
- addon/content/contactDetail.jsx
- addon/content/conversationHeader.jsx
- addon/content/es-modules/components/svg-icon.js
- addon/content/messageActionButton.jsx
- addon/content/messageHeader.jsx
- addon/content/messageHeaderOptions.jsx
- addon/content/messageNotification.jsx
- addon/content/messageTags.jsx
- addon/content/stub.xhtml
- addon/content/svgIcon.jsx
- addon/tests/svgIcon.test.jsx
An `SvgIcon` component was added and all (save one) direct references to the `material-icon.svg` file have been abstracted away to `SvgIcon`.
*Very* basic rendering test has been added.
> Encapsulate all svg rendering into SvgIcon

- addon/content/messageIFrame.jsx
- addon/content/modules/conversation.js
- addon/content/modules/message.js
- addon/content/stub.js
- addon/content/stub.xhtml
`RTK.configureStore` has many advantages over `createStore`. For example, it automatically includes the `redux-thunk` middleware. It also includes serializability checks by default. 
The core of Conversations relies a few actions that pass non-serializable data. It will take some time to rework those components. Minimal exceptions were added for those actions. These exceptions should be removed when issue #1461 is resolved.
> Replace Redux.createStore with RTK.configureStore

- .travis.yml
- addon/content/es-modules/quoting.js
- addon/content/quoting.js
- addon/content/stub.compose-ui.js
- addon/tests/quoting.test.js
Add minimal tests for `Quoting` found in `quoting.js`. I don't have a good sample of different emails to pull from, so the tests consist of one real email and several made up ones. More should be added if someone has sample emails.
These APIs are called in exactly one place in `messageIFrame.jsx`. All methods could be consolidated to a single method `wrapBlockquotes` or something like that and then called once instead of being called in a sequence in `messageIFrame.jsx`.
All internal-use-only methods of `Quoting` have been prefixed with `_`. I think there are better ways to handle the quoting code. Right now it passes around a DOM and mutates it, which is no good if data needs to be passed between a webextension and the Thunderbird API. It would be nice if this turned into a string-based …
> Add tests for Quoting

- addon/content/conversationWrapper.jsx
`getLocaleDirection()` returns a promise. It needs to be unwrapped before being assigned to an html attribute.
> Unwrap text dir Promise value

- addon/content/attachments.jsx
- addon/content/conversationHeader.jsx
- addon/content/message.jsx
- addon/content/messageHeader.jsx
- addon/content/messageNotification.jsx
- addon/content/modules/conversation.js
- addon/content/modules/message.js
- addon/content/modules/misc.js
- addon/content/modules/plugins/lightning.js
- addon/content/reducer-messages.js
- addon/content/reducer-summary.js
- addon/content/reducer.js
* Merge thunks and actions into `summaryActions`
* Migrates `messages` actions to the RTK-based `createSlice` style.
Several of the reducers were refactors using modern Javascript.
The `msgSetIsJunk` should have the same functionality as the original code, but it seems wrong to me...Is this an unnoticed bug?
> Merge thunks and actions into `summaryActions`

- addon/experiment-api/contactsApi.js
I was getting `TypeError: context is undefined` on `msgWindowApi.js:364`
(See #1453)
After poking at it a little bit, I discovered that `msgWindowApi.js` is,
for whatever reason, actually calling the `monkeyPatchAllWindows()` from
`contactsApi.js` (!) which doesn't accept/passthru a `context` parameter.
Rather than solve the hard problem of namespacing/scoping the conflicting
function definitions, however, I simply took the path of least resistance
and added the `context` parameter to `contactsApi.js`.  :-}
> Work-around for missing "Remote Content" bar (#1453)

- docs/Development.md
```
$ npm test:jest
Unknown command: "test:jest"
Did you mean one of these?
npm run test:lint # run the "test:lint" package script
npm run test:jest # run the "test:jest" package script
```
> Fix command for a jest test in developer's guide

- addon/content/reducer/contacts.js
- addon/content/reducer/messageEnricher.js
- addon/tests/messages.test.js
Mailing lists with 'Mangle From' configuration swaps 'From' with the mailing list address and keeping the original sender in the 'Reply-To' header.  Currently only 'reply' and 'reply to list' options are available in this case, but there should be an option to reply to both the list and the original sender.
Taking the 'reply-to' header into account while checking for multiple "recipients" to fix the problem.
> Fixes #1913: Show 'reply all' option if reply-to is different from the sender

- addon/content/stubWrapper.js
Services.jsm is planned to be removed in Firefox 117 cycle in https://bugzilla.mozilla.org/show_bug.cgi?id=1780695 . Services global variable is in all system globals from version 104 https://bugzilla.mozilla.org/show_bug.cgi?id=1667455 , and those code doesn't have to import Services.jsm if the strict_min_version is 114.
> Use Services global variable

- addon/content/components/compose/composeWidget.css
- addon/content/components/compose/composeWidget.jsx
- addon/tests/compose.test.jsx
Fixes #1933 
Improve appearance of send button in conversation compose box. Improvements include:
- support for dark mode
- cursor and color change on hover (old design didn't react in any way)
- more padding and boxier design more in line with modern Thunderbird style
Comparison:
Current Light
Current Dark
New Light
New Dark
It seems like the surrounding box doesn't resize properly. The bottom edge of the button is close to the border and _maybe_ on some other machines it will stick out. I am not really well versed in HTML and CSS so I don't know how to fix the layout properly. However, this change as it is is still an improvement.
Future improvements should also include changing links `discard`, `Forward this conversation`, `Print this conversation` to button style. It seems like the UI …
> Improve appearance of quick reply send button

- addon/content/components/message/messageIFrame.mjs
This commit mitigates the issue of dark mode adaptability.
Adding one feature to the options to allow user to enable dark mode. Then the content in the conversation nodes will be adapted.
The solutions is inspired by this comment:
https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1611#issuecomment-2470675052
PS. 
1. I modified all the messages.json under locale, but all are English, feel free to change to the correct language.
2. When I tried to build the project, build.sh does not work well because of the error of `find . -E ...`. The regex expression seems not work, fixed it as well.
> Fix issue 1611: Add native theme support (& dark mode) to the message display
